#ifndef __STATUS_BUTTON_H__
#define __STATUS_BUTTON_H__

// Referred from adas_service/adas_main/adas_main.h
typedef enum boolObjects_t {
    STATUS_BTN_CTRL,
    STATUS_BTN_CALIB,
    STATUS_BTN_PARAM,
    STATUS_BTN_CAPTURE,
    STATUS_BTN_LANE_GRAYSCALE,
    STATUS_BTN_SLIDING_WINDOW,
    STATUS_BTN_LOCALIZATION,
    STATUS_BTN_LANE_DETECT,
    STATUS_BTN_OBJ_ENABLE,
    STATUS_BTN_OBJ_CLASS,
    STATUS_BTN_OBJ_DISTANCE,
    STATUS_BTN_UNDISTOR,
    STATUS_BTN_SEND_CONTROL_MSG,
    STATUS_BTN_START_SERVER,
    STATUS_BTN_LANE_KEEPING_SYSTEM,
    STATUS_BTN_ADAPTIVE_CRUISE_CONTROL,
    STATUS_BTN_AUTO_EMERGENCY_BRAKING,
    STATUS_BTN_DETACH_AUTO_BRAKE
}boolObjects;

typedef enum intObjects_t {
    VALUE_SLIDER_STEER,
    VALUE_LINE_EDIT_STEER,
    VALUE_LINE_EDIT_THROTTLE,
    VALUE_SLIDER_THROTTLE,
    VALUE_LINE_EDIT_BRAKE,
    VALUE_SLIDER_BRAKE
} intObjects;

typedef enum controlMsgAttributeType_t
{
    ATTRIBUTE_BRAKE,
    ATTRIBUTE_STEER,
    ATTRIBUTE_THROTTLE,
    ATTRIBUTE_GEAR,
    ATTRIBUTE_DEFAULT
} controlMsgAttributeType;

#endif // __STATUS_BUTTON_H__