/**
 * @file tesla.c
 *
 * @brief This source file was generated by cantools version 41.0.2 Wed Jan  7 10:30:11 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "tesla.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int tesla_eps_driver_control_pack(
    uint8_t *dst_p,
    const struct tesla_eps_driver_control_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->eps_brake_pedal_pos, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->eps_accel_pedal_pos, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->eps_gear_lever_pos, 5u, 0xe0u);
    dst_p[3] |= pack_left_shift_u16(src_p->eps_steering_angle, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->eps_steering_angle, 8u, 0xffu);

    return (8);
}

int tesla_eps_driver_control_unpack(
    struct tesla_eps_driver_control_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->eps_brake_pedal_pos = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->eps_accel_pedal_pos = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->eps_gear_lever_pos = unpack_right_shift_u8(src_p[2], 5u, 0xe0u);
    dst_p->eps_steering_angle = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->eps_steering_angle |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);

    return (0);
}

int tesla_eps_driver_control_init(struct tesla_eps_driver_control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tesla_eps_driver_control_t));

    return 0;
}

uint8_t tesla_eps_driver_control_eps_brake_pedal_pos_encode(double value)
{
    return (uint8_t)(value / 0.4);
}

double tesla_eps_driver_control_eps_brake_pedal_pos_decode(uint8_t value)
{
    return ((double)value * 0.4);
}

bool tesla_eps_driver_control_eps_brake_pedal_pos_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

uint8_t tesla_eps_driver_control_eps_accel_pedal_pos_encode(double value)
{
    return (uint8_t)(value / 0.4);
}

double tesla_eps_driver_control_eps_accel_pedal_pos_decode(uint8_t value)
{
    return ((double)value * 0.4);
}

bool tesla_eps_driver_control_eps_accel_pedal_pos_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

uint8_t tesla_eps_driver_control_eps_gear_lever_pos_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_driver_control_eps_gear_lever_pos_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_driver_control_eps_gear_lever_pos_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint16_t tesla_eps_driver_control_eps_steering_angle_encode(double value)
{
    return (uint16_t)((value - -42.59775) / 0.0013);
}

double tesla_eps_driver_control_eps_steering_angle_decode(uint16_t value)
{
    return (((double)value * 0.0013) + -42.59775);
}

bool tesla_eps_driver_control_eps_steering_angle_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int tesla_eps_button_status_pack(
    uint8_t *dst_p,
    const struct tesla_eps_button_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->eps_lks_state, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->eps_acc_state, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->eps_aeb_state, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->eps_disable_adas, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->eps_inc_speed_limit, 0u, 0x03u);
    dst_p[5] |= pack_left_shift_u8(src_p->eps_dec_speed_limit, 0u, 0x03u);
    dst_p[6] |= pack_left_shift_u8(src_p->eps_inc_dis_limit, 0u, 0x03u);
    dst_p[7] |= pack_left_shift_u8(src_p->eps_dec_dis_limit, 0u, 0x03u);

    return (8);
}

int tesla_eps_button_status_unpack(
    struct tesla_eps_button_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->eps_lks_state = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->eps_acc_state = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->eps_aeb_state = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->eps_disable_adas = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->eps_inc_speed_limit = unpack_right_shift_u8(src_p[4], 0u, 0x03u);
    dst_p->eps_dec_speed_limit = unpack_right_shift_u8(src_p[5], 0u, 0x03u);
    dst_p->eps_inc_dis_limit = unpack_right_shift_u8(src_p[6], 0u, 0x03u);
    dst_p->eps_dec_dis_limit = unpack_right_shift_u8(src_p[7], 0u, 0x03u);

    return (0);
}

int tesla_eps_button_status_init(struct tesla_eps_button_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tesla_eps_button_status_t));

    return 0;
}

uint8_t tesla_eps_button_status_eps_lks_state_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_button_status_eps_lks_state_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_button_status_eps_lks_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_eps_button_status_eps_acc_state_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_button_status_eps_acc_state_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_button_status_eps_acc_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_eps_button_status_eps_aeb_state_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_button_status_eps_aeb_state_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_button_status_eps_aeb_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_eps_button_status_eps_disable_adas_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_button_status_eps_disable_adas_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_button_status_eps_disable_adas_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_eps_button_status_eps_inc_speed_limit_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_button_status_eps_inc_speed_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_button_status_eps_inc_speed_limit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t tesla_eps_button_status_eps_dec_speed_limit_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_button_status_eps_dec_speed_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_button_status_eps_dec_speed_limit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t tesla_eps_button_status_eps_inc_dis_limit_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_button_status_eps_inc_dis_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_button_status_eps_inc_dis_limit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t tesla_eps_button_status_eps_dec_dis_limit_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_button_status_eps_dec_dis_limit_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_button_status_eps_dec_dis_limit_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int tesla_eps_take_over_status_pack(
    uint8_t *dst_p,
    const struct tesla_eps_take_over_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->eps_control_take_over, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->eps_aeb_take_over, 1u, 0x02u);

    return (8);
}

int tesla_eps_take_over_status_unpack(
    struct tesla_eps_take_over_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->eps_control_take_over = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->eps_aeb_take_over = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    return (0);
}

int tesla_eps_take_over_status_init(struct tesla_eps_take_over_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tesla_eps_take_over_status_t));

    return 0;
}

uint8_t tesla_eps_take_over_status_eps_control_take_over_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_take_over_status_eps_control_take_over_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_take_over_status_eps_control_take_over_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_eps_take_over_status_eps_aeb_take_over_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_take_over_status_eps_aeb_take_over_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_take_over_status_eps_aeb_take_over_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int tesla_adas_control_pack(
    uint8_t *dst_p,
    const struct tesla_adas_control_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->adas_steering_angle_request, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->adas_steering_angle_request, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->adas_throttle_request, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->adas_brake_request, 0u, 0xffu);

    return (8);
}

int tesla_adas_control_unpack(
    struct tesla_adas_control_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->adas_steering_angle_request = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->adas_steering_angle_request |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->adas_throttle_request = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->adas_brake_request = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

int tesla_adas_control_init(struct tesla_adas_control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tesla_adas_control_t));

    return 0;
}

uint16_t tesla_adas_control_adas_steering_angle_request_encode(double value)
{
    return (uint16_t)((value - -42.59775) / 0.0013);
}

double tesla_adas_control_adas_steering_angle_request_decode(uint16_t value)
{
    return (((double)value * 0.0013) + -42.59775);
}

bool tesla_adas_control_adas_steering_angle_request_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t tesla_adas_control_adas_throttle_request_encode(double value)
{
    return (uint8_t)(value / 0.4);
}

double tesla_adas_control_adas_throttle_request_decode(uint8_t value)
{
    return ((double)value * 0.4);
}

bool tesla_adas_control_adas_throttle_request_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

uint8_t tesla_adas_control_adas_brake_request_encode(double value)
{
    return (uint8_t)(value / 0.4);
}

double tesla_adas_control_adas_brake_request_decode(uint8_t value)
{
    return ((double)value * 0.4);
}

bool tesla_adas_control_adas_brake_request_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

int tesla_adas_warning_pack(
    uint8_t *dst_p,
    const struct tesla_adas_warning_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->adas_aeb_warning, 0u, 0x03u);
    dst_p[0] |= pack_left_shift_u8(src_p->adas_lane_exists, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->adas_lane_departure, 3u, 0x08u);

    return (8);
}

int tesla_adas_warning_unpack(
    struct tesla_adas_warning_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->adas_aeb_warning = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->adas_lane_exists = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->adas_lane_departure = unpack_right_shift_u8(src_p[0], 3u, 0x08u);

    return (0);
}

int tesla_adas_warning_init(struct tesla_adas_warning_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tesla_adas_warning_t));

    return 0;
}

uint8_t tesla_adas_warning_adas_aeb_warning_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_adas_warning_adas_aeb_warning_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_adas_warning_adas_aeb_warning_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t tesla_adas_warning_adas_lane_exists_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_adas_warning_adas_lane_exists_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_adas_warning_adas_lane_exists_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_adas_warning_adas_lane_departure_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_adas_warning_adas_lane_departure_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_adas_warning_adas_lane_departure_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int tesla_ss_state_motion_pack(
    uint8_t *dst_p,
    const struct tesla_ss_state_motion_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->ss_lateral_accel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->ss_lateral_accel, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->ss_longitudinal_accel, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(src_p->ss_longitudinal_accel, 6u, 0x7fu);
    dst_p[2] |= pack_left_shift_u16(src_p->ss_longitudinal_velocity, 7u, 0x80u);
    dst_p[3] |= pack_right_shift_u16(src_p->ss_longitudinal_velocity, 1u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->ss_longitudinal_velocity, 9u, 0x3fu);
    dst_p[4] |= pack_left_shift_u16(src_p->ss_lateral_velocity, 6u, 0xc0u);
    dst_p[5] |= pack_right_shift_u16(src_p->ss_lateral_velocity, 2u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->ss_lateral_velocity, 10u, 0x01u);
    dst_p[6] |= pack_left_shift_u16(src_p->ss_yaw_rate, 1u, 0xfeu);
    dst_p[7] |= pack_right_shift_u16(src_p->ss_yaw_rate, 7u, 0x07u);

    return (8);
}

int tesla_ss_state_motion_unpack(
    struct tesla_ss_state_motion_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ss_lateral_accel = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->ss_lateral_accel |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    dst_p->ss_longitudinal_accel = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->ss_longitudinal_accel |= unpack_left_shift_u16(src_p[2], 6u, 0x7fu);
    dst_p->ss_longitudinal_velocity = unpack_right_shift_u16(src_p[2], 7u, 0x80u);
    dst_p->ss_longitudinal_velocity |= unpack_left_shift_u16(src_p[3], 1u, 0xffu);
    dst_p->ss_longitudinal_velocity |= unpack_left_shift_u16(src_p[4], 9u, 0x3fu);
    dst_p->ss_lateral_velocity = unpack_right_shift_u16(src_p[4], 6u, 0xc0u);
    dst_p->ss_lateral_velocity |= unpack_left_shift_u16(src_p[5], 2u, 0xffu);
    dst_p->ss_lateral_velocity |= unpack_left_shift_u16(src_p[6], 10u, 0x01u);
    dst_p->ss_yaw_rate = unpack_right_shift_u16(src_p[6], 1u, 0xfeu);
    dst_p->ss_yaw_rate |= unpack_left_shift_u16(src_p[7], 7u, 0x07u);

    return (0);
}

int tesla_ss_state_motion_init(struct tesla_ss_state_motion_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tesla_ss_state_motion_t));

    return 0;
}

uint16_t tesla_ss_state_motion_ss_lateral_accel_encode(double value)
{
    return (uint16_t)((value - -3.069) / 0.006);
}

double tesla_ss_state_motion_ss_lateral_accel_decode(uint16_t value)
{
    return (((double)value * 0.006) + -3.069);
}

bool tesla_ss_state_motion_ss_lateral_accel_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t tesla_ss_state_motion_ss_longitudinal_accel_encode(double value)
{
    return (uint16_t)((value - -40.955) / 0.01);
}

double tesla_ss_state_motion_ss_longitudinal_accel_decode(uint16_t value)
{
    return (((double)value * 0.01) + -40.955);
}

bool tesla_ss_state_motion_ss_longitudinal_accel_is_in_range(uint16_t value)
{
    return (value <= 8191u);
}

uint16_t tesla_ss_state_motion_ss_longitudinal_velocity_encode(double value)
{
    return (uint16_t)((value - -85.1942) / 0.0052);
}

double tesla_ss_state_motion_ss_longitudinal_velocity_decode(uint16_t value)
{
    return (((double)value * 0.0052) + -85.1942);
}

bool tesla_ss_state_motion_ss_longitudinal_velocity_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

uint16_t tesla_ss_state_motion_ss_lateral_velocity_encode(double value)
{
    return (uint16_t)((value - -10.0303) / 0.0098);
}

double tesla_ss_state_motion_ss_lateral_velocity_decode(uint16_t value)
{
    return (((double)value * 0.0098) + -10.0303);
}

bool tesla_ss_state_motion_ss_lateral_velocity_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint16_t tesla_ss_state_motion_ss_yaw_rate_encode(double value)
{
    return (uint16_t)((value - -3.069) / 0.006);
}

double tesla_ss_state_motion_ss_yaw_rate_decode(uint16_t value)
{
    return (((double)value * 0.006) + -3.069);
}

bool tesla_ss_state_motion_ss_yaw_rate_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int tesla_ss_chassis_status_pack(
    uint8_t *dst_p,
    const struct tesla_ss_chassis_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->ss_wheel_angles, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->ss_wheel_angles, 8u, 0x07u);
    dst_p[1] |= pack_left_shift_u8(src_p->ss_gear_lever, 3u, 0x18u);

    return (8);
}

int tesla_ss_chassis_status_unpack(
    struct tesla_ss_chassis_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ss_wheel_angles = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->ss_wheel_angles |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);
    dst_p->ss_gear_lever = unpack_right_shift_u8(src_p[1], 3u, 0x18u);

    return (0);
}

int tesla_ss_chassis_status_init(struct tesla_ss_chassis_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tesla_ss_chassis_status_t));

    return 0;
}

uint16_t tesla_ss_chassis_status_ss_wheel_angles_encode(double value)
{
    return (uint16_t)((value - -0.71645) / 0.0007);
}

double tesla_ss_chassis_status_ss_wheel_angles_decode(uint16_t value)
{
    return (((double)value * 0.0007) + -0.71645);
}

bool tesla_ss_chassis_status_ss_wheel_angles_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint8_t tesla_ss_chassis_status_ss_gear_lever_encode(double value)
{
    return (uint8_t)(value - 1.0);
}

double tesla_ss_chassis_status_ss_gear_lever_decode(uint8_t value)
{
    return ((double)value + 1.0);
}

bool tesla_ss_chassis_status_ss_gear_lever_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int tesla_adas_state_pack(
    uint8_t *dst_p,
    const struct tesla_adas_state_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->adas_idle_state, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->adas_brake_state, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->adas_lks_state, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->adas_tja_state, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->adas_acc_state, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->adas_hwc_state, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->adas_tjc_state, 6u, 0x40u);

    return (8);
}

int tesla_adas_state_unpack(
    struct tesla_adas_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->adas_idle_state = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->adas_brake_state = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->adas_lks_state = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->adas_tja_state = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->adas_acc_state = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->adas_hwc_state = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->adas_tjc_state = unpack_right_shift_u8(src_p[0], 6u, 0x40u);

    return (0);
}

int tesla_adas_state_init(struct tesla_adas_state_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tesla_adas_state_t));

    return 0;
}

uint8_t tesla_adas_state_adas_idle_state_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_adas_state_adas_idle_state_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_adas_state_adas_idle_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_adas_state_adas_brake_state_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_adas_state_adas_brake_state_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_adas_state_adas_brake_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_adas_state_adas_lks_state_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_adas_state_adas_lks_state_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_adas_state_adas_lks_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_adas_state_adas_tja_state_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_adas_state_adas_tja_state_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_adas_state_adas_tja_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_adas_state_adas_acc_state_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_adas_state_adas_acc_state_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_adas_state_adas_acc_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_adas_state_adas_hwc_state_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_adas_state_adas_hwc_state_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_adas_state_adas_hwc_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t tesla_adas_state_adas_tjc_state_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_adas_state_adas_tjc_state_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_adas_state_adas_tjc_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int tesla_eps_alert_matrix_pack(
    uint8_t *dst_p,
    const struct tesla_eps_alert_matrix_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->eps_not_ok_to_start_drive, 0u, 0x01u);

    return (8);
}

int tesla_eps_alert_matrix_unpack(
    struct tesla_eps_alert_matrix_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->eps_not_ok_to_start_drive = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int tesla_eps_alert_matrix_init(struct tesla_eps_alert_matrix_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tesla_eps_alert_matrix_t));

    return 0;
}

uint8_t tesla_eps_alert_matrix_eps_not_ok_to_start_drive_encode(double value)
{
    return (uint8_t)(value);
}

double tesla_eps_alert_matrix_eps_not_ok_to_start_drive_decode(uint8_t value)
{
    return ((double)value);
}

bool tesla_eps_alert_matrix_eps_not_ok_to_start_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int tesla_adas_control_setting_pack(
    uint8_t *dst_p,
    const struct tesla_adas_control_setting_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->adas_speed_limit, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->adas_speed_limit, 8u, 0x07u);
    dst_p[2] |= pack_left_shift_u16(src_p->adas_dis_limit, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->adas_dis_limit, 8u, 0x03u);

    return (8);
}

int tesla_adas_control_setting_unpack(
    struct tesla_adas_control_setting_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->adas_speed_limit = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->adas_speed_limit |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);
    dst_p->adas_dis_limit = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->adas_dis_limit |= unpack_left_shift_u16(src_p[3], 8u, 0x03u);

    return (0);
}

int tesla_adas_control_setting_init(struct tesla_adas_control_setting_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct tesla_adas_control_setting_t));

    return 0;
}

uint16_t tesla_adas_control_setting_adas_speed_limit_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double tesla_adas_control_setting_adas_speed_limit_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool tesla_adas_control_setting_adas_speed_limit_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint16_t tesla_adas_control_setting_adas_dis_limit_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double tesla_adas_control_setting_adas_dis_limit_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool tesla_adas_control_setting_adas_dis_limit_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}
