/**
 * @file tesla.h
 *
 * @brief This header file was generated by cantools version 41.0.2 Wed Jan  7 10:30:11 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef TESLA_H
#define TESLA_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define TESLA_EPS_DRIVER_CONTROL_FRAME_ID (0x118u)
#define TESLA_EPS_BUTTON_STATUS_FRAME_ID (0x399u)
#define TESLA_EPS_TAKE_OVER_STATUS_FRAME_ID (0x329u)
#define TESLA_ADAS_CONTROL_FRAME_ID (0x2b9u)
#define TESLA_ADAS_WARNING_FRAME_ID (0x488u)
#define TESLA_SS_STATE_MOTION_FRAME_ID (0x101u)
#define TESLA_SS_CHASSIS_STATUS_FRAME_ID (0x155u)
#define TESLA_ADAS_STATE_FRAME_ID (0x32au)
#define TESLA_EPS_ALERT_MATRIX_FRAME_ID (0x35au)
#define TESLA_ADAS_CONTROL_SETTING_FRAME_ID (0x3f8u)

/* Frame lengths in bytes. */
#define TESLA_EPS_DRIVER_CONTROL_LENGTH (8u)
#define TESLA_EPS_BUTTON_STATUS_LENGTH (8u)
#define TESLA_EPS_TAKE_OVER_STATUS_LENGTH (8u)
#define TESLA_ADAS_CONTROL_LENGTH (8u)
#define TESLA_ADAS_WARNING_LENGTH (8u)
#define TESLA_SS_STATE_MOTION_LENGTH (8u)
#define TESLA_SS_CHASSIS_STATUS_LENGTH (8u)
#define TESLA_ADAS_STATE_LENGTH (8u)
#define TESLA_EPS_ALERT_MATRIX_LENGTH (8u)
#define TESLA_ADAS_CONTROL_SETTING_LENGTH (8u)

/* Extended or standard frame types. */
#define TESLA_EPS_DRIVER_CONTROL_IS_EXTENDED (0)
#define TESLA_EPS_BUTTON_STATUS_IS_EXTENDED (0)
#define TESLA_EPS_TAKE_OVER_STATUS_IS_EXTENDED (0)
#define TESLA_ADAS_CONTROL_IS_EXTENDED (0)
#define TESLA_ADAS_WARNING_IS_EXTENDED (0)
#define TESLA_SS_STATE_MOTION_IS_EXTENDED (0)
#define TESLA_SS_CHASSIS_STATUS_IS_EXTENDED (0)
#define TESLA_ADAS_STATE_IS_EXTENDED (0)
#define TESLA_EPS_ALERT_MATRIX_IS_EXTENDED (0)
#define TESLA_ADAS_CONTROL_SETTING_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define TESLA_EPS_BUTTON_STATUS_EPS_LKS_STATE_DONT_PRESS_CHOICE (0u)
#define TESLA_EPS_BUTTON_STATUS_EPS_LKS_STATE_PRESS_CHOICE (1u)

#define TESLA_EPS_BUTTON_STATUS_EPS_ACC_STATE_DONT_PRESS_CHOICE (0u)
#define TESLA_EPS_BUTTON_STATUS_EPS_ACC_STATE_PRESS_CHOICE (1u)

#define TESLA_EPS_BUTTON_STATUS_EPS_AEB_STATE_DONT_PRESS_CHOICE (0u)
#define TESLA_EPS_BUTTON_STATUS_EPS_AEB_STATE_PRESS_CHOICE (1u)

#define TESLA_EPS_BUTTON_STATUS_EPS_DISABLE_ADAS_DONT_PRESS_CHOICE (0u)
#define TESLA_EPS_BUTTON_STATUS_EPS_DISABLE_ADAS_PRESS_CHOICE (1u)

#define TESLA_EPS_BUTTON_STATUS_EPS_INC_SPEED_LIMIT_DONT_PRESS_CHOICE (0u)
#define TESLA_EPS_BUTTON_STATUS_EPS_INC_SPEED_LIMIT_SHORT_PRESS_CHOICE (1u)
#define TESLA_EPS_BUTTON_STATUS_EPS_INC_SPEED_LIMIT_LONG_PRESS_CHOICE (2u)

#define TESLA_EPS_BUTTON_STATUS_EPS_DEC_SPEED_LIMIT_DONT_PRESS_CHOICE (0u)
#define TESLA_EPS_BUTTON_STATUS_EPS_DEC_SPEED_LIMIT_SHORT_PRESS_CHOICE (1u)
#define TESLA_EPS_BUTTON_STATUS_EPS_DEC_SPEED_LIMIT_LONG_PRESS_CHOICE (2u)

#define TESLA_EPS_BUTTON_STATUS_EPS_INC_DIS_LIMIT_DONT_PRESS_CHOICE (0u)
#define TESLA_EPS_BUTTON_STATUS_EPS_INC_DIS_LIMIT_SHORT_PRESS_CHOICE (1u)
#define TESLA_EPS_BUTTON_STATUS_EPS_INC_DIS_LIMIT_LONG_PRESS_CHOICE (2u)

#define TESLA_EPS_BUTTON_STATUS_EPS_DEC_DIS_LIMIT_DONT_PRESS_CHOICE (0u)
#define TESLA_EPS_BUTTON_STATUS_EPS_DEC_DIS_LIMIT_SHORT_PRESS_CHOICE (1u)
#define TESLA_EPS_BUTTON_STATUS_EPS_DEC_DIS_LIMIT_LONG_PRESS_CHOICE (2u)

#define TESLA_DI_DRIVER_SYSTEM_STATUS_DI_GEAR_DI_GEAR_INVALID_CHOICE (0u)
#define TESLA_DI_DRIVER_SYSTEM_STATUS_DI_GEAR_DI_GEAR_P_CHOICE (1u)
#define TESLA_DI_DRIVER_SYSTEM_STATUS_DI_GEAR_DI_GEAR_R_CHOICE (2u)
#define TESLA_DI_DRIVER_SYSTEM_STATUS_DI_GEAR_DI_GEAR_N_CHOICE (3u)
#define TESLA_DI_DRIVER_SYSTEM_STATUS_DI_GEAR_DI_GEAR_D_CHOICE (4u)
#define TESLA_DI_DRIVER_SYSTEM_STATUS_DI_GEAR_DI_GEAR_SNA_CHOICE (5u)

#define TESLA_DAS_STATUS_DAS_AUTOPILOT_STATE_IDLE_CHOICE (0u)
#define TESLA_DAS_STATUS_DAS_AUTOPILOT_STATE_ACC_ACTIVE_CHOICE (1u)
#define TESLA_DAS_STATUS_DAS_AUTOPILOT_STATE_LKA_ACTIVE_CHOICE (2u)
#define TESLA_DAS_STATUS_DAS_AUTOPILOT_STATE_TJC_ACTIVE_CHOICE (3u)
#define TESLA_DAS_STATUS_DAS_AUTOPILOT_STATE_TJA_ACTIVE_CHOICE (4u)
#define TESLA_DAS_STATUS_DAS_AUTOPILOT_STATE_HWC_ACTIVE_CHOICE (5u)

#define TESLA_DAS_STATUS_DAS_AEB_STATE_AEB_DISABLE_CHOICE (0u)
#define TESLA_DAS_STATUS_DAS_AEB_STATE_AEB_ENABLE_CHOICE (1u)
#define TESLA_DAS_STATUS_DAS_AEB_STATE_AEB_ERROR_CHOICE (2u)

/* Frame Names. */
#define TESLA_EPS_DRIVER_CONTROL_NAME "EPS_DriverControl"
#define TESLA_EPS_BUTTON_STATUS_NAME "EPS_ButtonStatus"
#define TESLA_EPS_TAKE_OVER_STATUS_NAME "EPS_TakeOverStatus"
#define TESLA_ADAS_CONTROL_NAME "ADAS_Control"
#define TESLA_ADAS_WARNING_NAME "ADAS_Warning"
#define TESLA_SS_STATE_MOTION_NAME "SS_StateMotion"
#define TESLA_SS_CHASSIS_STATUS_NAME "SS_ChassisStatus"
#define TESLA_ADAS_STATE_NAME "ADAS_State"
#define TESLA_EPS_ALERT_MATRIX_NAME "EPS_AlertMatrix"
#define TESLA_ADAS_CONTROL_SETTING_NAME "ADAS_ControlSetting"

/* Signal Names. */
#define TESLA_EPS_DRIVER_CONTROL_EPS_BRAKE_PEDAL_POS_NAME "EPS_brakePedalPos"
#define TESLA_EPS_DRIVER_CONTROL_EPS_ACCEL_PEDAL_POS_NAME "EPS_accelPedalPos"
#define TESLA_EPS_DRIVER_CONTROL_EPS_GEAR_LEVER_POS_NAME "EPS_gearLeverPos"
#define TESLA_EPS_DRIVER_CONTROL_EPS_STEERING_ANGLE_NAME "EPS_steeringAngle"
#define TESLA_EPS_BUTTON_STATUS_EPS_LKS_STATE_NAME "EPS_lksState"
#define TESLA_EPS_BUTTON_STATUS_EPS_ACC_STATE_NAME "EPS_accState"
#define TESLA_EPS_BUTTON_STATUS_EPS_AEB_STATE_NAME "EPS_aebState"
#define TESLA_EPS_BUTTON_STATUS_EPS_DISABLE_ADAS_NAME "EPS_disableAdas"
#define TESLA_EPS_BUTTON_STATUS_EPS_INC_SPEED_LIMIT_NAME "EPS_incSpeedLimit"
#define TESLA_EPS_BUTTON_STATUS_EPS_DEC_SPEED_LIMIT_NAME "EPS_decSpeedLimit"
#define TESLA_EPS_BUTTON_STATUS_EPS_INC_DIS_LIMIT_NAME "EPS_incDisLimit"
#define TESLA_EPS_BUTTON_STATUS_EPS_DEC_DIS_LIMIT_NAME "EPS_decDisLimit"
#define TESLA_EPS_TAKE_OVER_STATUS_EPS_CONTROL_TAKE_OVER_NAME "EPS_CONTROL_takeOver"
#define TESLA_EPS_TAKE_OVER_STATUS_EPS_AEB_TAKE_OVER_NAME "EPS_AEB_takeOver"
#define TESLA_ADAS_CONTROL_ADAS_STEERING_ANGLE_REQUEST_NAME "ADAS_steeringAngleRequest"
#define TESLA_ADAS_CONTROL_ADAS_THROTTLE_REQUEST_NAME "ADAS_throttleRequest"
#define TESLA_ADAS_CONTROL_ADAS_BRAKE_REQUEST_NAME "ADAS_brakeRequest"
#define TESLA_ADAS_WARNING_ADAS_AEB_WARNING_NAME "ADAS_aebWarning"
#define TESLA_ADAS_WARNING_ADAS_LANE_EXISTS_NAME "ADAS_laneExists"
#define TESLA_ADAS_WARNING_ADAS_LANE_DEPARTURE_NAME "ADAS_laneDeparture"
#define TESLA_SS_STATE_MOTION_SS_LATERAL_ACCEL_NAME "SS_lateralAccel"
#define TESLA_SS_STATE_MOTION_SS_LONGITUDINAL_ACCEL_NAME "SS_longitudinalAccel"
#define TESLA_SS_STATE_MOTION_SS_LONGITUDINAL_VELOCITY_NAME "SS_longitudinalVelocity"
#define TESLA_SS_STATE_MOTION_SS_LATERAL_VELOCITY_NAME "SS_lateralVelocity"
#define TESLA_SS_STATE_MOTION_SS_YAW_RATE_NAME "SS_yawRate"
#define TESLA_SS_CHASSIS_STATUS_SS_WHEEL_ANGLES_NAME "SS_wheelAngles"
#define TESLA_SS_CHASSIS_STATUS_SS_GEAR_LEVER_NAME "SS_gearLever"
#define TESLA_ADAS_STATE_ADAS_IDLE_STATE_NAME "ADAS_idleState"
#define TESLA_ADAS_STATE_ADAS_BRAKE_STATE_NAME "ADAS_brakeState"
#define TESLA_ADAS_STATE_ADAS_LKS_STATE_NAME "ADAS_lksState"
#define TESLA_ADAS_STATE_ADAS_TJA_STATE_NAME "ADAS_tjaState"
#define TESLA_ADAS_STATE_ADAS_ACC_STATE_NAME "ADAS_accState"
#define TESLA_ADAS_STATE_ADAS_HWC_STATE_NAME "ADAS_hwcState"
#define TESLA_ADAS_STATE_ADAS_TJC_STATE_NAME "ADAS_tjcState"
#define TESLA_EPS_ALERT_MATRIX_EPS_NOT_OK_TO_START_DRIVE_NAME "EPS_notOkToStartDrive"
#define TESLA_ADAS_CONTROL_SETTING_ADAS_SPEED_LIMIT_NAME "ADAS_speedLimit"
#define TESLA_ADAS_CONTROL_SETTING_ADAS_DIS_LIMIT_NAME "ADAS_disLimit"

/**
 * Signals in message EPS_DriverControl.
 *
 * All signal values are as on the CAN bus.
 */
struct tesla_eps_driver_control_t {
    /**
     * Range: 0..250 (0..100 %)
     * Scale: 0.4
     * Offset: 0
     */
    uint8_t eps_brake_pedal_pos;

    /**
     * Range: 0..250 (0..100 %)
     * Scale: 0.4
     * Offset: 0
     */
    uint8_t eps_accel_pedal_pos;

    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_gear_lever_pos;

    /**
     * Range: 0..65535 (-42.59775..42.59775 degree)
     * Scale: 0.0013
     * Offset: -42.59775
     */
    uint16_t eps_steering_angle;
};

/**
 * Signals in message EPS_ButtonStatus.
 *
 * All signal values are as on the CAN bus.
 */
struct tesla_eps_button_status_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_lks_state;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_acc_state;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_aeb_state;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_disable_adas;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_inc_speed_limit;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_dec_speed_limit;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_inc_dis_limit;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_dec_dis_limit;
};

/**
 * Signals in message EPS_TakeOverStatus.
 *
 * All signal values are as on the CAN bus.
 */
struct tesla_eps_take_over_status_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_control_take_over;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_aeb_take_over;
};

/**
 * Signals in message ADAS_Control.
 *
 * All signal values are as on the CAN bus.
 */
struct tesla_adas_control_t {
    /**
     * Range: 0..65535 (-42.59775..42.59775 degree)
     * Scale: 0.0013
     * Offset: -42.59775
     */
    uint16_t adas_steering_angle_request;

    /**
     * Range: 0..250 (0..100 %)
     * Scale: 0.4
     * Offset: 0
     */
    uint8_t adas_throttle_request;

    /**
     * Range: 0..250 (0..100 %)
     * Scale: 0.4
     * Offset: 0
     */
    uint8_t adas_brake_request;
};

/**
 * Signals in message ADAS_Warning.
 *
 * All signal values are as on the CAN bus.
 */
struct tesla_adas_warning_t {
    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t adas_aeb_warning;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t adas_lane_exists;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t adas_lane_departure;
};

/**
 * Signals in message SS_StateMotion.
 *
 * All signal values are as on the CAN bus.
 */
struct tesla_ss_state_motion_t {
    /**
     * Range: 0..1023 (-3.069..3.069 m/s^2)
     * Scale: 0.006
     * Offset: -3.069
     */
    uint16_t ss_lateral_accel;

    /**
     * Range: 0..8191 (-40.955..40.955 m/s^2)
     * Scale: 0.01
     * Offset: -40.955
     */
    uint16_t ss_longitudinal_accel;

    /**
     * Range: 0..32767 (-85.1942..85.1942 m/s)
     * Scale: 0.0052
     * Offset: -85.1942
     */
    uint16_t ss_longitudinal_velocity;

    /**
     * Range: 0..2047 (-10.0303..10.0303 m/s)
     * Scale: 0.0098
     * Offset: -10.0303
     */
    uint16_t ss_lateral_velocity;

    /**
     * Range: 0..1023 (-3.069..3.069 rad/s)
     * Scale: 0.006
     * Offset: -3.069
     */
    uint16_t ss_yaw_rate;
};

/**
 * Signals in message SS_ChassisStatus.
 *
 * All signal values are as on the CAN bus.
 */
struct tesla_ss_chassis_status_t {
    /**
     * Range: 0..2047 (-0.71645..0.71645 rad)
     * Scale: 0.0007
     * Offset: -0.71645
     */
    uint16_t ss_wheel_angles;

    /**
     * Range: 0..3 (1..4 -)
     * Scale: 1
     * Offset: 1
     */
    uint8_t ss_gear_lever;
};

/**
 * Signals in message ADAS_State.
 *
 * All signal values are as on the CAN bus.
 */
struct tesla_adas_state_t {
    /**
     * Range: 0..1 (0..1 True/False)
     * Scale: 1
     * Offset: 0
     */
    uint8_t adas_idle_state;

    /**
     * Range: 0..1 (0..1 True/False)
     * Scale: 1
     * Offset: 0
     */
    uint8_t adas_brake_state;

    /**
     * Range: 0..1 (0..1 True/False)
     * Scale: 1
     * Offset: 0
     */
    uint8_t adas_lks_state;

    /**
     * Range: 0..1 (0..1 True/False)
     * Scale: 1
     * Offset: 0
     */
    uint8_t adas_tja_state;

    /**
     * Range: 0..1 (0..1 True/False)
     * Scale: 1
     * Offset: 0
     */
    uint8_t adas_acc_state;

    /**
     * Range: 0..1 (0..1 True/False)
     * Scale: 1
     * Offset: 0
     */
    uint8_t adas_hwc_state;

    /**
     * Range: 0..1 (0..1 True/False)
     * Scale: 1
     * Offset: 0
     */
    uint8_t adas_tjc_state;
};

/**
 * Signals in message EPS_AlertMatrix.
 *
 * All signal values are as on the CAN bus.
 */
struct tesla_eps_alert_matrix_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t eps_not_ok_to_start_drive;
};

/**
 * Signals in message ADAS_ControlSetting.
 *
 * All signal values are as on the CAN bus.
 */
struct tesla_adas_control_setting_t {
    /**
     * Range: 0..2047 (0..204.7 km/h)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t adas_speed_limit;

    /**
     * Range: 0..1023 (0..102.3 m)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t adas_dis_limit;
};

/**
 * Pack message EPS_DriverControl.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tesla_eps_driver_control_pack(
    uint8_t *dst_p,
    const struct tesla_eps_driver_control_t *src_p,
    size_t size);

/**
 * Unpack message EPS_DriverControl.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tesla_eps_driver_control_unpack(
    struct tesla_eps_driver_control_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EPS_DriverControl.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tesla_eps_driver_control_init(struct tesla_eps_driver_control_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_driver_control_eps_brake_pedal_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_driver_control_eps_brake_pedal_pos_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_driver_control_eps_brake_pedal_pos_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_driver_control_eps_accel_pedal_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_driver_control_eps_accel_pedal_pos_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_driver_control_eps_accel_pedal_pos_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_driver_control_eps_gear_lever_pos_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_driver_control_eps_gear_lever_pos_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_driver_control_eps_gear_lever_pos_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tesla_eps_driver_control_eps_steering_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_driver_control_eps_steering_angle_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_driver_control_eps_steering_angle_is_in_range(uint16_t value);

/**
 * Pack message EPS_ButtonStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tesla_eps_button_status_pack(
    uint8_t *dst_p,
    const struct tesla_eps_button_status_t *src_p,
    size_t size);

/**
 * Unpack message EPS_ButtonStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tesla_eps_button_status_unpack(
    struct tesla_eps_button_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EPS_ButtonStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tesla_eps_button_status_init(struct tesla_eps_button_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_button_status_eps_lks_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_button_status_eps_lks_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_button_status_eps_lks_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_button_status_eps_acc_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_button_status_eps_acc_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_button_status_eps_acc_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_button_status_eps_aeb_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_button_status_eps_aeb_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_button_status_eps_aeb_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_button_status_eps_disable_adas_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_button_status_eps_disable_adas_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_button_status_eps_disable_adas_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_button_status_eps_inc_speed_limit_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_button_status_eps_inc_speed_limit_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_button_status_eps_inc_speed_limit_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_button_status_eps_dec_speed_limit_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_button_status_eps_dec_speed_limit_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_button_status_eps_dec_speed_limit_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_button_status_eps_inc_dis_limit_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_button_status_eps_inc_dis_limit_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_button_status_eps_inc_dis_limit_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_button_status_eps_dec_dis_limit_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_button_status_eps_dec_dis_limit_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_button_status_eps_dec_dis_limit_is_in_range(uint8_t value);

/**
 * Pack message EPS_TakeOverStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tesla_eps_take_over_status_pack(
    uint8_t *dst_p,
    const struct tesla_eps_take_over_status_t *src_p,
    size_t size);

/**
 * Unpack message EPS_TakeOverStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tesla_eps_take_over_status_unpack(
    struct tesla_eps_take_over_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EPS_TakeOverStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tesla_eps_take_over_status_init(struct tesla_eps_take_over_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_take_over_status_eps_control_take_over_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_take_over_status_eps_control_take_over_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_take_over_status_eps_control_take_over_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_take_over_status_eps_aeb_take_over_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_take_over_status_eps_aeb_take_over_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_take_over_status_eps_aeb_take_over_is_in_range(uint8_t value);

/**
 * Pack message ADAS_Control.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tesla_adas_control_pack(
    uint8_t *dst_p,
    const struct tesla_adas_control_t *src_p,
    size_t size);

/**
 * Unpack message ADAS_Control.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tesla_adas_control_unpack(
    struct tesla_adas_control_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ADAS_Control.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tesla_adas_control_init(struct tesla_adas_control_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tesla_adas_control_adas_steering_angle_request_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_control_adas_steering_angle_request_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_control_adas_steering_angle_request_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_control_adas_throttle_request_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_control_adas_throttle_request_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_control_adas_throttle_request_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_control_adas_brake_request_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_control_adas_brake_request_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_control_adas_brake_request_is_in_range(uint8_t value);

/**
 * Pack message ADAS_Warning.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tesla_adas_warning_pack(
    uint8_t *dst_p,
    const struct tesla_adas_warning_t *src_p,
    size_t size);

/**
 * Unpack message ADAS_Warning.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tesla_adas_warning_unpack(
    struct tesla_adas_warning_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ADAS_Warning.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tesla_adas_warning_init(struct tesla_adas_warning_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_warning_adas_aeb_warning_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_warning_adas_aeb_warning_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_warning_adas_aeb_warning_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_warning_adas_lane_exists_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_warning_adas_lane_exists_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_warning_adas_lane_exists_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_warning_adas_lane_departure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_warning_adas_lane_departure_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_warning_adas_lane_departure_is_in_range(uint8_t value);

/**
 * Pack message SS_StateMotion.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tesla_ss_state_motion_pack(
    uint8_t *dst_p,
    const struct tesla_ss_state_motion_t *src_p,
    size_t size);

/**
 * Unpack message SS_StateMotion.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tesla_ss_state_motion_unpack(
    struct tesla_ss_state_motion_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from SS_StateMotion.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tesla_ss_state_motion_init(struct tesla_ss_state_motion_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tesla_ss_state_motion_ss_lateral_accel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_ss_state_motion_ss_lateral_accel_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_ss_state_motion_ss_lateral_accel_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tesla_ss_state_motion_ss_longitudinal_accel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_ss_state_motion_ss_longitudinal_accel_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_ss_state_motion_ss_longitudinal_accel_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tesla_ss_state_motion_ss_longitudinal_velocity_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_ss_state_motion_ss_longitudinal_velocity_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_ss_state_motion_ss_longitudinal_velocity_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tesla_ss_state_motion_ss_lateral_velocity_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_ss_state_motion_ss_lateral_velocity_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_ss_state_motion_ss_lateral_velocity_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tesla_ss_state_motion_ss_yaw_rate_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_ss_state_motion_ss_yaw_rate_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_ss_state_motion_ss_yaw_rate_is_in_range(uint16_t value);

/**
 * Pack message SS_ChassisStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tesla_ss_chassis_status_pack(
    uint8_t *dst_p,
    const struct tesla_ss_chassis_status_t *src_p,
    size_t size);

/**
 * Unpack message SS_ChassisStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tesla_ss_chassis_status_unpack(
    struct tesla_ss_chassis_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from SS_ChassisStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tesla_ss_chassis_status_init(struct tesla_ss_chassis_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tesla_ss_chassis_status_ss_wheel_angles_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_ss_chassis_status_ss_wheel_angles_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_ss_chassis_status_ss_wheel_angles_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_ss_chassis_status_ss_gear_lever_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_ss_chassis_status_ss_gear_lever_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_ss_chassis_status_ss_gear_lever_is_in_range(uint8_t value);

/**
 * Pack message ADAS_State.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tesla_adas_state_pack(
    uint8_t *dst_p,
    const struct tesla_adas_state_t *src_p,
    size_t size);

/**
 * Unpack message ADAS_State.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tesla_adas_state_unpack(
    struct tesla_adas_state_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ADAS_State.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tesla_adas_state_init(struct tesla_adas_state_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_state_adas_idle_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_state_adas_idle_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_state_adas_idle_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_state_adas_brake_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_state_adas_brake_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_state_adas_brake_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_state_adas_lks_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_state_adas_lks_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_state_adas_lks_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_state_adas_tja_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_state_adas_tja_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_state_adas_tja_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_state_adas_acc_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_state_adas_acc_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_state_adas_acc_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_state_adas_hwc_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_state_adas_hwc_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_state_adas_hwc_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_adas_state_adas_tjc_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_state_adas_tjc_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_state_adas_tjc_state_is_in_range(uint8_t value);

/**
 * Pack message EPS_AlertMatrix.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tesla_eps_alert_matrix_pack(
    uint8_t *dst_p,
    const struct tesla_eps_alert_matrix_t *src_p,
    size_t size);

/**
 * Unpack message EPS_AlertMatrix.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tesla_eps_alert_matrix_unpack(
    struct tesla_eps_alert_matrix_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EPS_AlertMatrix.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tesla_eps_alert_matrix_init(struct tesla_eps_alert_matrix_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t tesla_eps_alert_matrix_eps_not_ok_to_start_drive_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_eps_alert_matrix_eps_not_ok_to_start_drive_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_eps_alert_matrix_eps_not_ok_to_start_drive_is_in_range(uint8_t value);

/**
 * Pack message ADAS_ControlSetting.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int tesla_adas_control_setting_pack(
    uint8_t *dst_p,
    const struct tesla_adas_control_setting_t *src_p,
    size_t size);

/**
 * Unpack message ADAS_ControlSetting.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int tesla_adas_control_setting_unpack(
    struct tesla_adas_control_setting_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ADAS_ControlSetting.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int tesla_adas_control_setting_init(struct tesla_adas_control_setting_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tesla_adas_control_setting_adas_speed_limit_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_control_setting_adas_speed_limit_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_control_setting_adas_speed_limit_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t tesla_adas_control_setting_adas_dis_limit_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double tesla_adas_control_setting_adas_dis_limit_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool tesla_adas_control_setting_adas_dis_limit_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
